name: CMake automatic build for multiple platforms

on:
    push:
        branches: ['dponyatov']
    pull_request:
        branches: ['dponyatov']

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - run: apt install -uy `cat apt.Ubuntu`
          - run: cmake --preset linux
          - run: cmake --build --preset linux
