name: CMake automatic build for multiple platforms

on:
    release:
        types: [published]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - run: sudo apt-get install -uy `cat apt.Ubuntu`
          - run: cmake --preset linux
          - run: cmake --build --preset linux
          - run: |
              APP=$(basename "$PWD")
              BRANCH=$(git rev-parse --abbrev-ref HEAD)
              DATE=$(date +%Y%m%d)
              HASH=$(git rev-parse --short=4 HEAD)
              NAME="${APP}_${BRANCH}_${DATE}_${HASH}"
              zip tmp/${NAME}.zip bin/*linux* bin/*win32* lib/*.ini lib/*.u || true
          - uses: softprops/action-gh-release@v1
            with:
              files: tmp/${NAME}.zip
              fail_on_unmatched_files: false
